config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  resources :kg_gallery_objects
  resources :kg_gallery_attributes

  match '/:controller/:action(/:slug)', :via => [:get]

  

  root :to => "application#index"
  
end

app/controllers/kg_gallery_attributes_controller.rb
class KgGalleryAttributesController < ApplicationController

  def index
    @kggas = KgGalleryAttribute.all
  end
  
  def new
    @kgga = KgGalleryAttribute.new
  end
  
  def create
    
    @kgga = KgGalleryAttribute.new(kgga_params)
    
    ap kgga_params
    @kgga.save
    redirect_to @kgga
  end
  
  def show
    @kgga = KgGalleryAttribute.find(params[:id])
  end
  
  private
  
  def kgga_params
    params.require(:kg_gallery_attribute).permit(:shortname, :name, :description, :datatype, :note, :has_choices, :has_multiple_choices, :internal_id)
  end
  
  
end

app/views/kg_gallery_attributes/index.html.erb
<ul>
<% @kggas.each do |kgga| %>
  
  <li><%= kgga.name %></li>
  
<% end %>
</ul>
  

app/views/kg_gallery_attributes/new.html.erb
<h2>Nouvel attribut</h2>

<%= form_for @kgga, url: kg_gallery_attributes_path, :html => { :multipart => true } do |f| %>
  <p>
    <%= f.label :shortname, "Nom court" %><br>
    <%= f.text_field :shortname %>
  </p>
  
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
  
  <p>
    <%= f.label :datatype, "Type de données" %><br>
    <%= f.text_field :datatype %>
  </p>
  
  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>
  
  <p>
    <%= f.label :has_choices, "Liste d’éléments" %><br>
    <%= f.check_box :has_choices %>
  </p>
  
  <p>
    <%= f.label :has_multiple_choices, "Liste d’éléments multiples" %><br>
    <%= f.check_box :has_multiple_choices %>
  </p>
  
  <p>
    <%= f.submit %>
  </p>
<% end %>