config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  resources :kg_gallery_objects
  resources :kg_gallery_attributes

  match '/:controller/:action(/:slug)', :via => [:get]

  

  root :to => "application#index"
  
end

app/models/kg_gallery_object.rb
class KgGalleryObject < ActiveRecord::Base
  def self.refresh_object_types
    @@default_value_by_object_type = {}
    @@attributes_by_object_type = {}
    @@attributes_shortnames_by_object_type = {}
    @@object_types = {}
    OBJECT_TYPES_FIXTURES.each do |object_type_shortname, kggas|
      @@default_value_by_object_type[object_type_shortname.to_s] = {}
      @@attributes_by_object_type[object_type_shortname.to_s] = {}
      @@attributes_shortnames_by_object_type[object_type_shortname.to_s] = []
      @@object_types[object_type_shortname.to_s] = {}
      @@object_types[object_type_shortname.to_s][:name] = {}
      name_fallback = object_type_shortname
      if kggas[:name]
        if kggas[:name].respond_to?(:has_key?)
          kggas[:name].each do |locale, name|
            @@object_types[object_type_shortname.to_s][:name][locale.to_sym] = name
          end
          name_fallback = nil
        else
          name_fallback = kggas[:name]
        end
      end
      if name_fallback
        Rails.application.config.i18n.available_locales.each do |locale|
          @@object_types[object_type_shortname.to_s][:name][locale.to_sym] = name_fallback
        end
      end
      if kggas[:attributes]
        kggas[:attributes].each do |kgga_shortname, kgga_options|
          @@attributes_by_object_type[object_type_shortname.to_s][kgga_shortname.to_s] = KgGalleryAttribute.where(:shortname => kgga_shortname.to_s).first
          @@attributes_shortnames_by_object_type[object_type_shortname.to_s].push(kgga_shortname.to_s)
          if kgga_options && kgga_options[:default]
            @@default_value_by_object_type[object_type_shortname.to_s][kgga_shortname.to_s] = kgga_options[:default]
          end
        end
      end
    end
  end
  OBJECT_TYPES_FIXTURES = (KgToolkit.recursive_symbolize_keys(KgToolkit.yml_file_to_hash("#{Rails.application.config.gallery_config_path}/object_types.yml")))[:object_types] rescue nil
  belongs_to :file, :class_name => "KgGalleryFile"
  belongs_to :author, :class_name => "User"
  accepts_nested_attributes_for :file
  validates_presence_of :object_type_shortname
  after_save :set_default_attribute_values
  include KgGalleryAttributable
  refresh_object_types
  
  def self.default_value_by_object_type
    @@default_value_by_object_type
  end
  
  def self.object_types
    @@object_types
  end
  
  def self.object_types_for_select
    self.object_types.inject([]){|select_array, (object_type_shortname, object_type_name)| select_array.push([object_type_name[:name][I18n.locale.to_sym], object_type_shortname])}
  end
  
  def associated_attributes
    @@attributes_by_object_type[object_type_shortname.to_s]
  end
  
  def associated_attributes_shortnames
    @@attributes_shortnames_by_object_type[object_type_shortname.to_s]
  end
  
  private
  
  def set_default_attribute_values
    if @@default_value_by_object_type[object_type_shortname]
      @@default_value_by_object_type[object_type_shortname].each do |kgga_shortname, kgga_default_value|
        send(kgga_shortname.to_s+"=", kgga_default_value) if (send(kgga_shortname)).nil?
      end
    end
  end
  
  
  
end

app/controllers/kg_gallery_objects_controller.rb
class KgGalleryObjectsController < ApplicationController
  
  def index
    @kggos = KgGalleryObject.all
  end
  
  def new
    object_type_shortname = params[:type]
    @kggo = KgGalleryObject.new(:object_type_shortname => object_type_shortname)
    @kggas = @kggo.associated_attributes
    @kggo.build_file
  end
  
  def create
    @kggo = KgGalleryObject.new(kggo_params)
    @kggas = @kggo.associated_attributes
    @kggo.associated_attributes_shortnames.each do |kgga_shortname|
      if(kggo_params[kgga_shortname])
        @kggo.send(kgga_shortname, kggo_params[kgga_shortname])
      end
    end
    @kggo.save
    redirect_to @kggo
  end
  
  def show
    @kggo = KgGalleryObject.find(params[:id])
    render :layout => "application_no_footer"
  end
  
  private
  
  def kggo_params
    params.require(:kg_gallery_object).permit(:name, :description, :shortname, :object_type_shortname, :file_attributes => [:id, :shortname, :name, :description, :filename, :url, :filetype])
  end
  
  
  
end

app/helpers/kg_gallery_objects_helper.rb
module KgGalleryObjectsHelper
end

app/views/kg_gallery_objects/index.html.erb
<div class="line">
  
  <% @kggos.select{ |kggo| kggo.file && kggo.file.filename }.each do |kggo| %>
  <div class="thumb">
    <div class="photo" style="background: no-repeat center center url(<%= image_path kggo.file.filename.url(:thumb) %>) #0b0d11"><a href="<%= url_for(kg_gallery_object_path(:id => kggo.id)) %>" class="a_photo" title="Agrandir cette photo">&nbsp;</a></div>
    <p class="p_photo"><span><a href="<%= url_for(kg_gallery_object_path(:id => kggo.id)) %>" class="s_a_photo" title="Agrandir cette photo"><%= kggo.name || kggo.file.filename_file_name %></a></span></p>
  </div>
  <% end %>
  
</div>

app/views/kg_gallery_objects/new.html.erb
<h2><%= t(:new_object).capitalize_first_char %></h2>

<%= form_for @kggo, url: kg_gallery_objects_path, :html => { :multipart => true } do |f| %>
  <p>
    <%= f.label :shortname %><br>
    <%= f.text_field :shortname %>
  </p>
  
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
  
  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>
  
  <p>
    <%= f.label :object_type_shortname %><br>
    <%= f.select :object_type_shortname, KgGalleryObject.object_types_for_select %>
  </p>
  
  <% @kggas.each do |kgga_shortname, kgga| %>
  <p>
    <%= f.label kgga_shortname.to_sym %><br>
    <% if kgga.has_choices %>
      <%= f.collection_select kgga_shortname.to_sym, KgGalleryAttributeChoice.where(:attribute_sn => kgga_shortname.to_sym), :shortname, :name %>
    <% else %>
      <%= f.text_field kgga_shortname.to_sym %>
    <% end %>
  </p>
  <% end %>
  
  <%= f.fields_for :file do |file_form| %>
    <p>
      <%= file_form.label :filename %>
      <%= file_form.file_field :filename %>
    </p>
  <% end %>
  
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/kg_gallery_objects/show.html.erb
    <div class="frame">
      <div class="d_browse_legend">
        <div class="d_browse_nav">
          <p class="hide"><img src="<%= image_path("browse_empty_icon.gif") %>" alt="*" />&nbsp;<a href="?img=17&amp;line=2&amp;album=225&amp;id=5086" title="Photo précédente" class="a_albums_back"><img src="<%= image_path("browse_prev_arrow.gif") %>" /></a>&nbsp;&nbsp;&nbsp;&nbsp;1 / 18&nbsp;&nbsp;&nbsp;&nbsp;<a href="?img=1&amp;line=2&amp;album=225&amp;id=5092" title="Photo suivante" class="a_albums_back"><img src="<%= image_path("browse_next_arrow.gif") %>" /></a>&nbsp;<a href="?img=17&amp;line=2&amp;album=225&amp;id=5086" title="Dernière photo" class="a_albums_back"><img src="<%= image_path("browse_last_arrow.gif") %>" /></a></p>
        </div>
        <div class="d_clear"></div>
      </div>
      <% if @kggo.file %><div class="browse_photo"><a href="" class="a_frame_image"><img id="object_main_image" src="<%= @kggo.file.filename.url(:large) %>" alt="*" /></a></div><% end %>
      <h2 class="h_browse_title"><%= @kggo.name %></h2>
    </div>
    <div class="d_browse_caption">
      <!-- <dl class="dl_download">
        <dt class="dt_download"><a href="" title="" class="a_download">Télécharger l&#8217;original</a></dt>
        <dd class="dd_download">Document JPG 533 X 800 pixels</dd>
      </dl> -->
    </div>
    
  </div>
</div> <!-- Container End -->

<hr class="hidden" />

<!-- Footer -->
<div id="footer">
  <div id="ornement_bottom"></div>
  <div class="d_info" style="width: 876px;">
  	<table class="t_info" style="width: 487px;">
  		<tr class="tr_author">
  			<th>Auteur</th><td>Pierre-Léo Bourbonnais</td>
  		</tr>
  		<tr class="tr_date">
  		  <th>Date et heure</th><td>2013.05.01 07:25:12</td>
  	  </tr>
	
  	  <tr>
  	  	<th>ID</th><td>2013_05_01__MG_8603</td>
  	  </tr>
  	  	<tr>
  	  	<th>Caméra</th><td>Canon EOS 7D</td>
  	  </tr>
  	  			<tr>
  	  	<th>Exposition</th><td>1/2000 s</td>
  	  </tr>
  	  		<tr>
  	  	<th>Sensibilité ISO</th><td>400</td>
  	  </tr>
  	  		<tr>
  	  	<th>Longueur focale</th><td>200 mm</td>
  	  </tr>
  	  		<tr>
  	  	<th>Profondeur de champ</th><td>f5.6</td>
  	  </tr>
  	</table>
  	<div class="d_info_left" style="width: 351px;">
  		<div class="d_star_rating" style="width: 65px;">
  			<ul class="ul_star_rating">
  				<li class="current-rating" style="width: 13px;">1</li>
  				<li><a href="?img=1&line=2&album=224&amp;rating=1" title="1" class="one-star">1</a></li>
  				<li><a href="?img=1&line=2&album=224&amp;rating=2" title="2" class="two-stars">2</a></li>
  				<li><a href="?img=1&line=2&album=224&amp;rating=3" title="3" class="three-stars">3</a></li>
  				<li><a href="?img=1&line=2&album=224&amp;rating=4" title="4" class="four-stars">4</a></li>
  				<li><a href="?img=1&line=2&album=224&amp;rating=5" title="5" class="five-stars">5</a></li>
  			</ul>
  			<p style="text-align: right; padding-top: 0.2em;">1&nbsp;/&nbsp;5<br /><em>1 vote</em></p>
  		</div>
  		<h3>Grèce</h3>
		
  		<h4>Litochoron, <em>Thessalie</em></h4>
  		<dl>
  			<dt>Mots clés</dt>
  			<dd>montagne, mont, olympe.</dd>
  			<dt>Thèmes</dt>
  			<dd><a href="themes.php?id=13" class="a_browse_themes">Paysage</a> &#8212; <a href="themes.php?id=1" class="a_browse_themes">Voyage</a></dd>
  		</dl>
  	</div>
  </div>
  <p class="f_copyright oblique">MIT License</p>
  <div class="clear"></div>
</div>
<!-- Footer End -->